import { Inter } from "@next/font/google";
import Head from "next/head";
import AboutCompany from "../components/AboutCompany/AboutCompany";
import NavBar from "../components/NavBar/NavBar";
import ProgrammingTechnologies from "../components/ProgrammingTechnologies/ProgrammingTechnologies";
import ReportContactForm from "../components/ReportContactForm/ReportContactForm";
import ShortDescription from "../components/ShortDescription/ShortDescription";
import styles from "../styles/Home.module.scss";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Report form</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className={styles.mainWrapper}>
        <NavBar />
      </header>
      <main className={styles.mainWrapper}>
        <ShortDescription />
        <AboutCompany />
        <ProgrammingTechnologies />
        {/* somthing else */}
        <ReportContactForm />
      </main>
      <footer className={styles.mainWrapper}>FOOTER</footer>
    </>
  );
}
